name: 'Chromatic'

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/design-system
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Run Chromatic
        run: yarn chromatic
        env:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
